# Generated by Django 4.2.3 on 2023-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='jugadores_list',
            field=models.ManyToManyField(related_name='equipos_inscritos', to='configuraciones.jugadores'),
        ),
    ]
