# Generated by Django 4.2.3 on 2023-07-30 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_equipo_jugadores_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='enfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=50)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='configuraciones.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='configuraciones.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='enfrentamientoJugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfrentamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.enfrentamiento')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.jugadores')),
            ],
        ),
    ]
