# Generated by Django 4.2.3 on 2023-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_enfrentamiento_enfrentamientojugadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='jugadores_list',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='correo',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='posicion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
