# Generated by Django 4.2.3 on 2023-07-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_remove_equipo_jugadores_list_remove_jugadores_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfrentamientojugadores',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='enfrentamientojugadores',
            name='jugador',
        ),
    ]
