# Generated by Django 4.2.3 on 2023-07-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0006_rename_pais_equipo_liga'),
    ]

    operations = [
        migrations.CreateModel(
            name='ligas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='liga',
        ),
    ]
