# Generated by Django 4.2.3 on 2023-07-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0007_ligas_remove_equipo_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ligas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.ligas'),
        ),
    ]
