# Generated by Django 4.2.3 on 2023-07-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0008_equipo_ligas'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='camiseta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
