# Generated by Django 4.2.3 on 2023-07-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0010_competencia_equipos_registrados_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='competencia',
        ),
    ]
