# Generated by Django 4.2.3 on 2023-08-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0011_delete_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligas',
            name='equipos',
            field=models.ManyToManyField(related_name='ligas_inscritas', to='configuraciones.equipo'),
        ),
    ]
