# Generated by Django 4.2.3 on 2023-08-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0013_remove_ligas_equipos_alter_equipo_ligas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligas',
            name='modo',
            field=models.CharField(choices=[('individual', 'Modo Individual'), ('grupal', 'Modo Grupal')], default='individual', max_length=10),
        ),
    ]
